### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Padmapriya-09** [cecileloge/cs229-RecoBook#3]
hey, i am unable to access files from your bucket.. It is saying you do not have storage.objects.list access to the Google Cloud Storage bucket. If possible can you give access to your bucket??

**Comment by cecileloge** [comment]
Hi Padma, no unfortunately the buckets don't exist anymore, this was a private project storing data on Google Cloud - which can be costly - and I've closed the account.
The datasets are listed in the README doc!
