### ISSUE TITLE
metadata in dataset

### ISSUE THREAD

**Issue by Padmapriya-09** [cecileloge/cs229-RecoBook#4]

**Comment by Padmapriya-09** [comment]
Hello, Can I please know from where have you got the "metadata" from which has 'genre, tag cloud, book snippet,..etc' columns in it. I have not found this in either of the links given in description

**Comment by cecileloge** [comment]
The book snippets are from the Kaggle dataset (it's the book description - extracted from the back cover), the genre is from the other dataset (I combined them both).
Please have a thorough look! Thank you!
